-- 001: the schema as it was in SQLite on 2026-09-12, translated for PostgreSQL.
-- Timestamps stay epoch doubles; booleans stay integer 0/1 (spec 2026-09-11 §1,
-- deviation ruled 2026-09-12). Everything is schema-qualified; public stays empty.

-- ---------------------------------------------------------------- learning DB

create table if not exists rehoboam.auction_outcomes (
    id                  bigint generated by default as identity primary key,
    player_id           text not null,
    player_name         text not null,
    our_bid             bigint not null,
    asking_price        bigint not null,
    our_overbid_pct     double precision not null,
    won                 integer not null,
    winning_bid         bigint,
    winning_overbid_pct double precision,
    winner_user_id      text,
    "timestamp"         double precision not null,
    player_value_score  double precision,
    market_value        bigint
);
create index if not exists idx_auction_outcomes_player_id on rehoboam.auction_outcomes (player_id);
create index if not exists idx_auction_outcomes_timestamp on rehoboam.auction_outcomes ("timestamp");

create table if not exists rehoboam.flip_outcomes (
    id             bigint generated by default as identity primary key,
    player_id      text not null,
    player_name    text not null,
    buy_price      bigint not null,
    sell_price     bigint not null,
    profit         bigint not null,
    profit_pct     double precision not null,
    hold_days      integer not null,
    buy_date       double precision not null,
    sell_date      double precision not null,
    trend_at_buy   text,
    average_points double precision,
    position       text,
    was_injured    integer not null default 0
);
create index if not exists idx_flip_outcomes_player_id on rehoboam.flip_outcomes (player_id);
create index if not exists idx_flip_outcomes_buy_date on rehoboam.flip_outcomes (buy_date);
create unique index if not exists idx_flip_unique on rehoboam.flip_outcomes (player_id, buy_date);

create table if not exists rehoboam.matchday_outcomes (
    id                           bigint generated by default as identity primary key,
    player_id                    text not null,
    player_position              text not null,
    matchday_date                text not null,
    predicted_ep                 double precision not null,
    actual_points                double precision not null,
    was_in_best_11               integer default 0,
    opponent_strength            text,
    purchase_price               bigint,
    marginal_ep_gain_at_purchase double precision,
    "timestamp"                  text default to_char(now() at time zone 'utc', 'YYYY-MM-DD HH24:MI:SS'),
    unique (player_id, matchday_date)
);
create index if not exists idx_matchday_outcomes_player on rehoboam.matchday_outcomes (player_id);
create index if not exists idx_matchday_outcomes_position on rehoboam.matchday_outcomes (player_position);

create table if not exists rehoboam.pending_bids (
    player_id          text primary key,
    player_name        text not null,
    our_bid            bigint not null,
    asking_price        bigint not null,
    our_overbid_pct    double precision not null,
    "timestamp"        double precision not null,
    market_value       bigint,
    player_value_score double precision
);
create index if not exists idx_pending_bids_timestamp on rehoboam.pending_bids ("timestamp");

create table if not exists rehoboam.pending_bid_sell_plans (
    pending_bid_player_id text not null,
    sell_player_id        text not null,
    primary key (pending_bid_player_id, sell_player_id)
);

create table if not exists rehoboam.tracked_purchases (
    player_id   text primary key,
    player_name text not null,
    buy_price   bigint not null,
    buy_date    double precision not null,
    source      text
);
create index if not exists idx_tracked_purchases_buy_date on rehoboam.tracked_purchases (buy_date);

create table if not exists rehoboam.recently_sold (
    player_id   text primary key,
    player_name text not null,
    sold_price  bigint not null,
    sold_at     double precision not null,
    reason      text
);
create index if not exists idx_recently_sold_sold_at on rehoboam.recently_sold (sold_at);

create table if not exists rehoboam.predicted_eps (
    player_id        text not null,
    league_id        text not null,
    predicted_at     double precision not null,
    predicted_ep     double precision not null,
    position         text not null,
    was_in_best_11   integer not null default 0,
    marginal_ep_gain double precision,
    primary key (player_id, predicted_at)
);
create index if not exists idx_predicted_eps_player_at on rehoboam.predicted_eps (player_id, predicted_at);

create table if not exists rehoboam.team_value_history (
    snapshot_at double precision primary key,
    league_id   text not null,
    team_value  bigint not null,
    budget      bigint not null,
    squad_size  integer not null
);

create table if not exists rehoboam.player_mv_history (
    player_id     text not null,
    snapshot_at   double precision not null,
    market_value  bigint not null,
    peak_mv_30d   bigint,
    trough_mv_30d bigint,
    primary key (player_id, snapshot_at)
);
create index if not exists idx_player_mv_history_player on rehoboam.player_mv_history (player_id, snapshot_at);

create table if not exists rehoboam.matchday_lineup_results (
    league_id         text not null,
    day_number        integer not null,
    matchday_date     text not null,
    total_points      integer not null,
    lineup_player_ids text not null,
    lineup_count      integer not null,
    snapshot_at       double precision not null,
    primary key (league_id, day_number)
);

create table if not exists rehoboam.league_rank_history (
    snapshot_at     double precision not null,
    league_id       text not null,
    manager_id      text not null,
    day_number      integer not null,
    rank_overall    integer,
    rank_matchday   integer,
    total_points    integer,
    matchday_points integer,
    team_value      bigint,
    is_self         integer not null default 0,
    primary key (snapshot_at, manager_id)
);
create index if not exists idx_league_rank_self_at on rehoboam.league_rank_history (is_self, snapshot_at);

create table if not exists rehoboam.manager_profile_history (
    snapshot_at   double precision not null,
    league_id     text not null,
    manager_id    text not null,
    transfer_pnl  bigint not null,
    matchday_wins integer,
    is_self       integer not null default 0,
    primary key (snapshot_at, manager_id)
);
create index if not exists idx_manager_profile_self_at on rehoboam.manager_profile_history (is_self, snapshot_at);

create table if not exists rehoboam.buy_decisions (
    id               bigint generated by default as identity primary key,
    "timestamp"      double precision not null,
    player_id        text not null,
    player_name      text,
    decision         text not null,
    reason           text not null,
    marginal_ep_gain double precision,
    asking_price     bigint,
    market_value     bigint,
    budget_ceiling   bigint
);
create index if not exists idx_buy_decisions_at on rehoboam.buy_decisions ("timestamp");

create table if not exists rehoboam.manager_transfers (
    league_id      text not null,
    manager_id     text not null,
    transfer_dt    text not null,
    player_id      text not null,
    player_name    text not null,
    transfer_type  integer,
    transfer_price bigint,
    primary key (league_id, manager_id, transfer_dt, player_id)
);
create index if not exists idx_manager_transfers_mgr_dt on rehoboam.manager_transfers (manager_id, transfer_dt);

create table if not exists rehoboam.forced_sales (
    matchday    integer primary key,
    place       integer not null,
    player_id   text not null,
    player_name text not null,
    pool        text not null,
    reason      text not null,
    executed    integer not null,
    settled_at  double precision not null
);

create table if not exists rehoboam.trade_proposals (
    proposal_id  text primary key,
    player_id    text not null,
    player_name  text not null,
    bid          bigint not null,
    market_value bigint not null,
    message      text not null,
    status       text not null,
    created_at   double precision not null
);

create table if not exists rehoboam.league_transfers (
    id                   bigint generated by default as identity primary key,
    activity_id          text unique not null,
    player_id            text not null,
    player_name          text not null,
    buyer_name           text,
    seller_name          text,
    transfer_price       bigint not null,
    transfer_type        integer not null,
    market_value_at_time bigint,
    overbid_pct          double precision,
    "timestamp"          text not null,
    processed_at         double precision not null
);
create index if not exists idx_league_transfers_player on rehoboam.league_transfers (player_id);
create index if not exists idx_league_transfers_timestamp on rehoboam.league_transfers ("timestamp");
create index if not exists idx_league_transfers_buyer on rehoboam.league_transfers (buyer_name);

create table if not exists rehoboam.market_value_snapshots (
    id           bigint generated by default as identity primary key,
    activity_id  text unique not null,
    player_id    text not null,
    player_name  text not null,
    market_value bigint not null,
    "timestamp"  text not null,
    processed_at double precision not null
);
create index if not exists idx_mv_snapshots_player on rehoboam.market_value_snapshots (player_id);

-- ------------------------------------------------------------------- corpus

create table if not exists rehoboam.player_universe (
    player_id      text primary key,
    first_name     text,
    last_name      text,
    position       text,
    team_id        text,
    market_value   bigint,
    average_points double precision
);

create table if not exists rehoboam.player_match_history (
    player_id        text not null,
    season           text not null,
    day_number       integer not null,
    match_date       text,
    points           integer not null,
    minutes          integer not null,
    team_id          text,
    opponent_team_id text,
    is_home           integer not null default 0,
    -- per-match availability label from the performance payload's `st`
    -- (1 not in squad, 3 sub on, 4 unused sub, 5 started; 0 future; null absent)
    status           integer,
    primary key (player_id, season, day_number)
);
create index if not exists idx_match_history_player on rehoboam.player_match_history (player_id, season, day_number);

create table if not exists rehoboam.mv_series (
    player_id    text not null,
    snapshot_at  double precision not null,
    market_value bigint not null,
    primary key (player_id, snapshot_at)
);

create table if not exists rehoboam.sweep_progress (
    player_id              text primary key,
    performance_fetched_at double precision,
    mv_fetched_at          double precision,
    transfers_fetched_at   double precision
);

create table if not exists rehoboam.player_transfers (
    player_id         text not null,
    transfer_at       double precision not null,
    price             bigint,
    transfer_type     integer,
    counterparty_id   text,
    counterparty_name text,
    primary key (player_id, transfer_at)
);
create index if not exists idx_player_transfers_player on rehoboam.player_transfers (player_id);

-- -------------------------------------------------------------------- cache
-- Replaces player_history.db's performance_cache (kind 'performance', key '')
-- and market_value_cache (kind 'mv', key = timeframe as text).

create table if not exists rehoboam.api_cache (
    kind       text not null,
    player_id  text not null,
    league_id  text not null,
    key        text not null default '',
    fetched_at double precision not null,
    payload    jsonb not null,
    primary key (kind, player_id, league_id, key)
);
create index if not exists idx_api_cache_fetched_at on rehoboam.api_cache (fetched_at);
