-- PR D: one row per run from either app, and what the integrity check found.
create table if not exists rehoboam.session_facts (
    session_id          text primary key,
    app                 text not null,            -- function | cli | external
    mode                text not null,            -- full | lineup_only | ingest | export
    dry_run             integer not null default 0,
    started_at          double precision not null,
    duration_s          double precision not null default 0,
    phase               text,
    next_kickoff        double precision,         -- epoch; null = unknown
    next_kickoff_source text,                     -- schedule | myeleven | none
    squad_gk            integer,
    squad_def           integer,
    squad_mid           integer,
    squad_fw            integer,
    fieldable_count     integer,
    legal_formation     text,
    budget              bigint,
    sellable_value      bigint,
    open_offers_total   bigint,
    open_offers_manual  bigint,
    cost_basis_missing  integer,
    predictions_written integer,
    lineup_result       text,                     -- set | dry_run | illegal | failed | skipped
    errors              integer not null default 0,
    error_text          text not null default '',
    extra               jsonb
);
create index if not exists idx_session_facts_app_started on rehoboam.session_facts (app, started_at);

create table if not exists rehoboam.integrity_failures (
    id         bigint generated by default as identity primary key,
    session_id text not null,
    rule       text not null,
    detail     text not null,
    created_at double precision not null
);
create index if not exists idx_integrity_failures_session on rehoboam.integrity_failures (session_id);
